
const mockResources = [
    {
      id: 1,
      name: "Akutboende Stockholm",
      opening_time: "08:00",
      closing_time: "20:00",
      address: "Stora Gatan 12",
      phone: "081 123 45 67",
      email: "kontakt@akutboende.se",
      target_group: "direct",
      other: "över 18, hemlöshet",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 2,
      name: "Mottagning Unga",
      opening_time: "10:00",
      closing_time: "16:00",
      address: "Lilla Vägen 5",
      phone: "081 456 78 59",
      email: "info@mottagningunga.se",
      target_group: "office",
      other: "under 18, otrygghet",
      applies_to: ["under18"],
      is_open_now: false,
    },
    {
      id: 3,
      name: "Hjälpcenter för utsatta",
      opening_time: "09:00",
      closing_time: "18:00",
      address: "Centralgatan 1",
      phone: "081 123 45 46",
      email: "support@hjalpcenter.se",
      target_group: "direct",
      other: "otrygghet, alla åldrar",
      applies_to: ["adult", "under18"],
      is_open_now: true,
    },
    {
      id: 4,
      name: "Mottagning Vuxna",
      opening_time: "11:00",
      closing_time: "17:00",
      address: "Exempelvägen 7",
      phone: "081 987 65 43",
      email: "kontakt@mottagningvuxna.se",
      target_group: "office",
      other: "över 18, psykisk ohälsa, missbruk",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 5,
      name: "Ungdomshälsan Väst",
      opening_time: "10:00",
      closing_time: "18:00",
      address: "Västergatan 22",
      phone: "081 555 11 02",
      email: "info@ungdomshalsan.se",
      target_group: "direct",
      other: "psykisk ohälsa, missbruk, alla åldrar",
      applies_to: ["under18"],
      is_open_now: false,
    },
    {
      id: 6,
      name: "Hälsocenter City",
      opening_time: "08:30",
      closing_time: "16:00",
      address: "Cityvägen 9",
      phone: "081 553 28 35",
      email: "kontakt@halsocenter.se",
      target_group: "office",
      other: "hälsa, sjukvård, alla åldrar",
      applies_to: ["adult", "under18"],
      is_open_now: false,
    },
    {
      id: 7,
      name: "Drop-in Krismottagning",
      opening_time: "11:00",
      closing_time: "20:00",
      address: "Kriskajen 1",
      phone: "081 245 87 95",
      email: "kris@dropin.se",
      target_group: "direct",
      other: "våld, ordningsstörning, över 18",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 8,
      name: "Migrationsstöd Stockholm",
      opening_time: "10:00",
      closing_time: "15:00",
      address: "Migrationstorget 3",
      phone: "081 356 54 12",
      email: "kontakt@migrationsstod.se",
      target_group: "office",
      other: "immigration, samverkan, över 18",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 9,
      name: "Sysselsättningscenter Norr",
      opening_time: "09:00",
      closing_time: "17:00",
      address: "Norrgatan 10",
      phone: "081 953 43 23",
      email: "jobb@norrcenter.se",
      target_group: "direct",
      other: "sysselsättning, psykisk ohälsa, under 18",
      applies_to: ["under18"],
      is_open_now: true,
    },
    {
      id: 10,
      name: "Stödboende Hoppet",
      opening_time: "07:00",
      closing_time: "19:00",
      address: "Hoppgatan 7",
      phone: "081 247 90 43",
      email: "kontakt@hoppet.se",
      target_group: "direct",
      other: "hemlöshet, missbruk, alla åldrar",
      applies_to: ["adult", "under18"],
      is_open_now: false,
    },
    {
      id: 11,
      name: "Ordningsjouren",
      opening_time: "00:00",
      closing_time: "23:59",
      address: "Jourvägen 1",
      phone: "081 593 13 77",
      email: "jour@ordningsjouren.se",
      target_group: "office",
      other: "ordningsstörning, kriminalitet, över 18",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 12,
      name: "Tunnelbaneteamet",
      opening_time: "12:00",
      closing_time: "20:00",
      address: "T-banegången 15",
      phone: "081 421 73 84",
      email: "kontakt@tunnelbanehjälp.se",
      target_group: "direct",
      other: "otrygghet, tunnelbana, under 18",
      applies_to: ["under18"],
      is_open_now: true,
    },
    {
      id: 13,
      name: "Kvinnojouren Öst",
      opening_time: "09:00",
      closing_time: "17:00",
      address: "Östergatan 2",
      phone: "081 934 24 12",
      email: "kontakt@kvinnojouren.se",
      target_group: "office",
      other: "våld, människohandel, över 18",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 14,
      name: "Akutstöd Centrum",
      opening_time: "08:00",
      closing_time: "22:00",
      address: "Centrumtorget 6",
      phone: "081 456 78 90",
      email: "akut@stodcentrum.se",
      target_group: "direct",
      other: "sjukvård, våldutsatthet, under 18",
      applies_to: ["under18"],
      is_open_now: true,
    },
    {
      id: 15,
      name: "Nattjour Nord",
      opening_time: "20:00",
      closing_time: "06:00",
      address: "Nattgatan 12",
      phone: "081 789 01 23",
      email: "nattjour@nord.se",
      target_group: "office",
      other: "hemlöshet, sysselsättning, över 18",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 16,
      name: "Trygg Familjehjälp",
      opening_time: "10:00",
      closing_time: "17:00",
      address: "Familjegatan 8",
      phone: "081 234 56 78",
      email: "familj@trygg.se",
      target_group: "direct",
      other: "otrygghet, psykisk ohälsa, samverkan",
      applies_to: ["adult", "under18"],
      is_open_now: true,
    },
    {
      id: 17,
      name: "Stödenheten Öst",
      opening_time: "09:00",
      closing_time: "15:00",
      address: "Östervägen 14",
      phone: "081 654 32 10",
      email: "kontakt@stodenheten.se",
      target_group: "office",
      other: "konflikter, immigration, alla åldrar",
      applies_to: ["adult", "under18"],
      is_open_now: false,
    },
    {
      id: 18,
      name: "Boendestöd City",
      opening_time: "07:00",
      closing_time: "19:00",
      address: "Stadsgatan 21",
      phone: "081 909 87 65",
      email: "boende@city.se",
      target_group: "direct",
      other: "missbruk, våld, över 18",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 19,
      name: "Rådgivningen Syd",
      opening_time: "11:00",
      closing_time: "16:00",
      address: "Sydvägen 4",
      phone: "081 882 11 33",
      email: "radgivning@syd.se",
      target_group: "office",
      other: "människohandel, psykisk ohälsa, våldutsatthet",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 20,
      name: "Jobbstart Ungdom",
      opening_time: "10:00",
      closing_time: "14:00",
      address: "Startgatan 2",
      phone: "081 775 66 22",
      email: "jobb@ung.se",
      target_group: "direct",
      other: "sysselsättning, under 18",
      applies_to: ["under18"],
      is_open_now: true,
    },
    {
      id: 21,
      name: "Krisstöd Väster",
      opening_time: "12:00",
      closing_time: "18:00",
      address: "Västergatan 3",
      phone: "081 662 44 88",
      email: "krisstod@vaster.se",
      target_group: "office",
      other: "ordningsstörning, konflikter, alla åldrar",
      applies_to: ["adult", "under18"],
      is_open_now: false,
    },
    {
      id: 22,
      name: "Integration Direkt",
      opening_time: "09:00",
      closing_time: "17:00",
      address: "Integrationsvägen 9",
      phone: "081 541 88 20",
      email: "info@integrationdirekt.se",
      target_group: "direct",
      other: "immigration, samverkan, vuxna",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 23,
      name: "Ungdomsstöd Mitt",
      opening_time: "08:00",
      closing_time: "16:00",
      address: "Mittvägen 10",
      phone: "081 312 99 77",
      email: "ungdom@stodmitt.se",
      target_group: "office",
      other: "psykisk ohälsa, våld, under 18",
      applies_to: ["under18"],
      is_open_now: true,
    },
    {
      id: 24,
      name: "Skyddsnät Stockholm",
      opening_time: "13:00",
      closing_time: "21:00",
      address: "Skyddsgatan 3",
      phone: "081 313 13 13",
      email: "kontakt@skyddsnat.se",
      target_group: "office",
      other: "människohandel, sjukvård, över 18",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 25,
      name: "Ungas Trygghet",
      opening_time: "15:00",
      closing_time: "22:00",
      address: "Ungdomstorget 9",
      phone: "081 423 23 23",
      email: "trygghet@ungas.se",
      target_group: "direct",
      other: "otrygghet, tunnelbana, konflikter",
      applies_to: ["under18"],
      is_open_now: false,
    },
    {
      id: 26,
      name: "Nattjour Sydväst",
      opening_time: "22:00",
      closing_time: "06:00",
      address: "Sydvästgatan 11",
      phone: "081 899 88 77",
      email: "natt@sydvast.se",
      target_group: "direct",
      other: "hemlöshet, ordningsstörning, över 18",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 27,
      name: "Familjestöd Östermalm",
      opening_time: "09:30",
      closing_time: "15:30",
      address: "Östermalmsgatan 20",
      phone: "081 777 77 66",
      email: "familj@ostermalm.se",
      target_group: "office",
      other: "våldutsatthet, konflikter, psykisk ohälsa",
      applies_to: ["adult", "under18"],
      is_open_now: false,
    },
    {
      id: 28,
      name: "Stadsmissionen Centrum",
      opening_time: "08:30",
      closing_time: "17:00",
      address: "Centrumgatan 5",
      phone: "081 321 67 89",
      email: "info@stadsmission.se",
      target_group: "direct",
      other: "sjukvård, hälsa, samverkan",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 29,
      name: "Psykjouren Väst",
      opening_time: "10:00",
      closing_time: "19:00",
      address: "Västgatan 15",
      phone: "081 453 78 91",
      email: "kontakt@psykjouren.se",
      target_group: "office",
      other: "psykisk ohälsa, suicidalitet, alla åldrar",
      applies_to: ["adult", "under18"],
      is_open_now: true,
    },
    {
      id: 30,
      name: "Boinfo Direkt",
      opening_time: "12:00",
      closing_time: "20:00",
      address: "Boendegatan 18",
      phone: "081 363 77 55",
      email: "info@boinfo.se",
      target_group: "direct",
      other: "boende, hemlöshet, samverkan",
      applies_to: ["adult"],
      is_open_now: false,
    },
    {
      id: 31,
      name: "Rättsjouren City",
      opening_time: "09:00",
      closing_time: "16:00",
      address: "Domstolsgatan 2",
      phone: "081 626 44 33",
      email: "ratt@jourcity.se",
      target_group: "office",
      other: "kriminalitet, otrygghet, ordningsstörning",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 32,
      name: "Flyktingcenter Syd",
      opening_time: "10:00",
      closing_time: "17:00",
      address: "Flyktgatan 6",
      phone: "081 475 65 43",
      email: "flykt@syd.se",
      target_group: "office",
      other: "immigration, samverkan, sjukvård",
      applies_to: ["adult", "under18"],
      is_open_now: false,
    },
    {
      id: 33,
      name: "Missbruksstöd Norr",
      opening_time: "08:00",
      closing_time: "18:00",
      address: "Norrgatan 13",
      phone: "081 593 47 38",
      email: "missbruk@norr.se",
      target_group: "direct",
      other: "missbruk, psykisk ohälsa, konflikter",
      applies_to: ["adult"],
      is_open_now: true,
    },
    {
      id: 34,
      name: "Polisen",
      opening_time: "24:00",
      closing_time: "00:00",
      address: "Fleminggatan 13",
      phone: "112",
      email: "hjälp@polisen.se",
      target_group: "direct",
      other: "suicid, psykisk ohälsa",
      applies_to: ["adult", "under18"],
      is_open_now: true,
    },
    
    
  ];
  
  export default mockResources;
  