// userSelectAccommodation.js
export const products_ = [
    {
        id: 45,
        name: "room",
        description: "5-bäddsrum",
        total_places: 5,
        type: "room",
    },
    {
        id: 46,
        name: "room",
        description: "3-bäddsrum",
        total_places: 3,
        type: "room"
    },
    {
        id: 47,
        name: "room",
        description: "7-bäddsrum",
        total_places: 7,
        type: "room"
    },
    {
        id: 48,
        name: "dormitory",
        description: "Dormitory - 10 beds",
        total_places: 10,
        type: "dormitory"
    },
    {
        id: 49,
        name: "apartment",
        description: "2-room apartment",
        total_places: 2,
        type: "apartment"
    }
];

// Define and export generateAvailableShelter function
export function generateAvailableShelter() {
    const hosts = [
        {
            region: { id: 3, name: "Stockholm City" },
            id: 3,
            name: "Grimmans Akutboende",
            street: "Parkgatan 48",
            postcode: "",
            city: "Sundbyberg",
            imageSrc: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: true,
            doubleRooms: true,
            dormitory: true,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast: true,
            dinner: true,
            storage :true,
            products: products_
        },
        {
            region: { id: 2, name: "Göteborg" },
            id: 4,
            name: "Fjällbohemmet",
            street: "Fjällgatan 5",
            postcode: "415 05",
            city: "Göteborg",
            imageSrc: "https://provinshus.se/wp-content/uploads/2018/08/Villa-Vinninge.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: true,
            doubleRooms: true,
            dormitory: true,
            shower: false,
            washing_machine: true,
            hygiene_articles: false,
            breakfast: true,
            dinner: true,
            storage : true,
            products: products_
        },
        {
            region: { id: 4, name: "Malmö" },
            id: 5,
            name: "Hyllie Akutboende",
            street: "Hyllievägen 32",
            postcode: "215 32",
            imageSrc: "https://www.alingsashuspaket.se/wp-content/uploads/2021/11/Hemma_hos_familjen_BertilssonEriksson_23.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms:true,
            doubleRooms: true,
            dormitory: false,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast:false,
            dinner: false,
            storage : true,
            city: "Malmö"
        },
        {
            region: { id: 1, name: "Uppsala" },
            id: 6,
            name: "Salagatan Härbärge",
            street: "Salagatan 10",
            postcode: "753 30",
            city: "Uppsala",
            imageSrc: "https://cdn.blog.boneo.se/wp-content/uploads/sites/16/2020/06/21062925/alabama11.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: false,
            doubleRooms: true,
            dormitory:true,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast: true,
            dinner: true,
            storage : true,
            products: products_
        },
        {
            region: { id: 6, name: "Västerås" },
            id: 7,
            name: "Råby Akutboende",
            street: "Råbyvägen 22",
            postcode: "724 60",
            city: "Västerås",
            imageSrc: "https://globalbar.se/wp-content/uploads/2021/05/ICON-3D-printade-hus.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: true,
            doubleRooms: false,
            dormitory: true,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast: true,
            dinner: true,
            storage : true,
            products: products_
        },
        {
            region: { id: 7, name: "Örebro" },
            id: 8,
            name: "Örebro Härbärge",
            street: "Drottninggatan 10",
            postcode: "702 10",
            city: "Örebro",
            imageSrc: "https://hjaltevadshus.se/app/uploads/2024/02/Hus-1-N2-small-1200x788.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: true,
            doubleRooms: true,
            dormitory: true,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast: true,
            dinner: false,
            storage : true,
            products: products_
        },
        {
            region: { id: 8, name: "Lund" },
            id: 9,
            name: "Stadsmissionens Boende",
            street: "Norra Fäladen 7",
            postcode: "223 61",
            city: "Lund",
            imageSrc: "https://hjaltevadshus.se/app/uploads/2024/02/Hus-2-N3-small-1200x923.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: false,
            doubleRooms: true,
            dormitory: false,
            shower: true,
            washing_machine: true,
            hygiene_articles: false,
            breakfast: true,
            dinner: true,
            storage : true,
            products: products_
        },
        {
            region: { id: 9, name: "Linköping" },
            id: 10,
            name: "Linköpings Härbärge",
            street: "Nygatan 14",
            postcode: "582 19",
            city: "Linköping",
            imageSrc: "https://mjobacks.se/images/hus/ladhus/Sok_Str%C3%A5vik_ext2.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: false,
            doubleRooms: true,
            dormitory: true,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast: true,
            dinner: true,
            storage : true,
            products: products_
        },
        {
            region: { id: 10, name: "Norrköping" },
            id: 11,
            name: "Norrköping Härbärge",
            street: "Gamla Rådstugugatan 7",
            postcode: "602 32",
            city: "Norrköping",
            imageSrc: "https://hjaltevadshus.se/app/uploads/2022/10/nyckelfardigt-hus-spira97.jpg",
            about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque velit ac quam scelerisque, ac ullamcorper lorem bibendum. Sed vehicula arcu ut nisi tincidunt, nec tempor dolor gravida. Integer fringilla ex ut fermentum facilisis. Fusce nec mauris non mauris venenatis ultricies a sed ipsum.",
            singlerooms: true,
            doubleRooms: true,
            dormitory: false,
            shower: true,
            washing_machine: true,
            hygiene_articles: true,
            breakfast: true,
            dinner: true,
            storage : true,
            products: products_
        }
    ];

    // Example function to generate available shelters
    return hosts; // Return the hosts array with products
}
