FROM node:22-alpine

WORKDIR /frontend

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN adduser -D app && chown -R app:app /frontend

USER app

EXPOSE 5173

CMD ["npm", "run", "dev:dev"]