export const regions = [
  "Stockholm",
  "Skåne",
  "Västmanland",
  "VästraGötaland",
  "Östergötland",
  "Södermanland",
  "Halland",
  "Örebro",
  "Jönköping",
  "Uppsala",
  "Blekinge",
  "Dalarna",
  "Norrbotten",
  "Gävleborg",
  "Kronoberg",
  "Kalmar",
  "Västerbotten",
  "Västernorrland",
  "Värmland",
  "Jämtland",
  "Gotland",
];

export const stockholmKommuner = [
  "Botkyrka",
  "Danderyd",
  "Ekerö",
  "Haninge",
  "Huddinge",
  "Järfälla",
  "Lidingö",
  "Nacka",
  "Norrtälje",
  "Nykvarn",
  "Nynäshamn",
  "Salem",
  "Sigtuna",
  "Sollentuna",
  "Solna",
  "Stockholm",
  "Sundbyberg",
  "Södertälje",
  "Tyresö",
  "Täby",
  "Upplands-Bro",
  "Upplands",
  "Väsby",
  "Vallentuna",
  "Vaxholm",
  "Värmdö",
  "Österåker",
];

export const skaneKommuner = [
  "Bjuv",
  "Bromölla",
  "Burlöv",
  "Båstad",
  "Eslöv",
  "Helsingborg",
  "Hässleholm",
  "Höganäs",
  "Hörby",
  "Höör",
  "Klippan",
  "Kristianstad",
  "Kävlinge",
  "Landskrona",
  "Lomma",
  "Lund",
  "Malmö",
  "Osby",
  "Perstorp",
  "Simrishamn",
  "Sjöbo",
  "Skurup",
  "Staffanstorp",
  "Svalöv",
  "Svedala",
  "Tomelilla",
  "Trelleborg",
  "Vellinge",
  "Ystad",
  "Åstorp",
  "Ängelholm",
  "Örkelljunga",
  "Östra Göinge",
];

export const vastmanlandKommuner = [
  "Arboga",
  "Fagersta",
  "Hallstahammar",
  "Kungsör",
  "Köping",
  "Norberg",
  "Sala",
  "Skinnskatteberg",
  "Surahammar",
  "Västerås",
];

export const vastraGotlandKommuner = [
  "Ale",
  "Alingsås",
  "Åmål",
  "Bengtsfors",
  "Bollebygd",
  "Borås",
  "Dals-Ed",
  "Essunga",
  "Falköping",
  "Färgelanda",
  "Götene",
  "Göteborg",
  "Grästorp",
  "Gullspång",
  "Härryda",
  "Herrljunga",
  "Hjo",
  "Karlsborg",
  "Kungälv",
  "Lerum",
  "Lidköping",
  "Lilla Edet",
  "Lysekil",
  "Mariestad",
  "Mark",
  "Mellerud",
  "Mölndal",
  "Munkedal",
  "Öckerö",
  "Orust",
  "Partille",
  "Skara",
  "Skövde",
  "Sotenäs",
  "Stenungsund",
  "Strömstad",
  "Svenljunga",
  "Tanum",
  "Tibro",
  "Tidaholm",
  "Tjörn",
  "Töreboda",
  "Tranemo",
  "Trollhättan",
  "Uddevalla",
  "Ulricehamn",
  "Vänersborg",
  "Vara",
  "Vårgårda",
];

export const ostergotlandKommuner = [
  "Boxholm",
  "Finspång",
  "Kinda",
  "Linköping",
  "Mjölby",
  "Motala",
  "Norrköping",
  "Söderköping",
  "Vadstena",
  "Valdemarsvik",
  "Ydre",
  "Åtvidaberg",
  "Ödeshög",
];

export const sodermandlandKommuner = [
  "Eskilstuna",
  "Flen",
  "Gnesta",
  "Katrineholm",
  "Nyköping",
  "Oxelösund",
  "Strängnäs",
  "Trosa",
  "Vingåker",
];

export const hallandKommuner = [
  "Falkenberg",
  "Halmstad",
  "Hylte",
  "Kungsbacka",
  "Laholm",
  "Varberg",
];

export const orbroKommuner = [
  "Askersund",
  "Degerfors",
  "Hallsberg",
  "Hällefors",
  "Karlskoga",
  "Kumla",
  "Laxå",
  "Lekeberg",
  "Lindesberg",
  "Ljusnarsberg",
  "Nora",
  "Örebro",
];

export const jonkopingKommuner = [
  "Aneby",
  "Eksjö",
  "Gislaved",
  "Gnosjö",
  "Habo",
  "Jönköping",
  "Mullsjö",
  "Nässjö",
  "Sävsjö",
  "Tranås",
  "Vaggeryd",
  "Värnamo",
  "Vetlanda",
];

export const uppsalaKommuner = [
  "Enköpings",
  "Heby",
  "Håbo",
  "Knivsta",
  "Tierps",
  "Uppsala",
  "Älvkarleby",
  "Östhammars",
];

export const blekingeKommuner = [
  "Karlshamn",
  "Karlskrona",
  "Olofström",
  "Ronneby",
  "Sölvesborg",
];

export const dalarnaKommuner = [
  "Avesta",
  "Borlänge",
  "Falun",
  "Gagnef",
  "Hedemora",
  "Leksand",
  "Ludvika",
  "Malung-Sälen",
  "Mora",
  "Orsa",
  "Rättvik",
  "Säter",
  "Smedjebacken",
  "Vansbro",
  "Älvdalen",
];

export const norrbottenKommuner = [
  "Älvsbyn",
  "Arjeplog",
  "Arvidsjaur",
  "Boden",
  "Gällivare",
  "Haparanda",
  "Jokkmokk",
  "Kalix",
  "Kiruna",
  "Luleå",
  "Överkalix",
  "Övertorneå",
  "Pajala",
  "Piteå",
];

export const gavleborgKommuner = [
  "Bollnäs",
  "Gävle",
  "Hofors",
  "Hudiksvall",
  "Ljusdal",
  "Nordanstig",
  "Ockelbo",
  "Ovanåker",
  "Sandviken",
  "Söderhamn",
];

export const kronobergKommuner = [
  "Alvesta",
  "Lessebo",
  "Ljungby",
  "Markaryd",
  "Tingsryd",
  "Uppvidinge",
  "Växjö",
  "Älmhult",
];

export const kalmarKommuner = [
  "Kalmar",
  "Alvesta",
  "Lessebo",
  "Ljungby",
  "Markaryd",
  "Tingsryd",
  "Uppvidinge",
  "Växjö",
  "Älmhult",
];

export const vasterbottenKommuner = [
  "Bjurholm",
  "Dorotea",
  "Lycksele",
  "Malå",
  "Nordmaling",
  "Norsjö",
  "Robertsfors",
  "Skellefteå",
  "Sorsele",
  "Storuman",
  "Umeå",
  "Vilhelmina",
  "Vindeln",
  "Vännäs",
  "Åsele",
];

export const vasternorrlandKommuner = [
  "Härnösand",
  "Kramfors",
  "Sollefteå",
  "Sundsvall",
  "Timrå",
  "Ånge",
  "Örnsköldsvik",
];

export const varmlandKommuner = [
  "Arvika",
  "Eda",
  "Filipstad",
  "Forshaga",
  "Grums",
  "Hagfors",
  "Hammarö",
  "Karlstad",
  "Kil",
  "Kristinehamn",
  "Munkfors",
  "Storfors",
  "Sunne",
  "Säffle",
  "Torsby",
  "Årjäng",
];

export const jamtlandKommuner = [
  "Åre",
  "Berg",
  "Bräcke",
  "Härjedalen",
  "Krokom",
  "Ragunda",
  "Strömsund",
  "Östersund",
];

export const gotlandKommuner = ["Gotland"];

export const kommunerMap = {
  Stockholm: stockholmKommuner,
  Skåne: skaneKommuner,
  Västmanland: vastmanlandKommuner,
  VästraGötaland: vastraGotlandKommuner,
  Östergötland: ostergotlandKommuner,
  Södermanland: sodermandlandKommuner,
  Halland: hallandKommuner,
  Örebro: orbroKommuner,
  Jönköping: jonkopingKommuner,
  Uppsala: uppsalaKommuner,
  Blekinge: blekingeKommuner,
  Dalarna: dalarnaKommuner,
  Norrbotten: norrbottenKommuner,
  Gävleborg: gavleborgKommuner,
  Kronoberg: kronobergKommuner,
  Kalmar: kalmarKommuner,
  Västerbotten: vasterbottenKommuner,
  Västernorrland: vasternorrlandKommuner,
  Värmland: varmlandKommuner,
  Jämtland: jamtlandKommuner,
  Gotland: gotlandKommuner,
};
