name: Build and Deploy Pipeline

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGTHSAIL_IP_ADDRESS }}
          username: ${{ secrets.LIGTHSAIL_USERNAME }}
          key: ${{ secrets.LIGTHSAIL_SSH_PRIVATE_KEY }}
          password: ""
          passphrase: ""
          port: 22
          script: |
            sudo apt-get install zip unzip
            unzip -q -o /home/${{ secrets.LIGTHSAIL_USERNAME }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }} -d /home/${{ secrets.LIGTHSAIL_USERNAME }}/${{ secrets.LIGTHSAIL_ROOT_DIR }}
            rm /home/${{ secrets.LIGTHSAIL_USERNAME }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }}
            sudo systemctl restart nginx




