name: Build and Deploy Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

      - name: Create zip deployment package
        run: zip -r deployment.zip ./dist/*

      - name: Copy deployment package to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP_ADDRESS }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          port: 22
          source: deployment.zip
          target: "/home/${{ secrets.LIGHTSAIL_USERNAME }}"
      
      # handle prject with sudo commands using appleboy/ssh-action@v0.1.7 
      # sudo like, unpack and install zip and restart nginx
      
