name: Build and Deploy Pipeline

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

      - name: Create zip deployment package
        run: zip -r deployment.zip ./dist/*

      - name: Copy deployment package to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP_ADDRESS }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          port: 22
          source: deployment.zip
          target: "/home/${{ secrets.LIGHTSAIL_USERNAME }}"

      - name: Verify SSH connection to Lightsail
        run: |
          ssh -i ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }} ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_IP_ADDRESS }} "echo 'SSH connection successful'"
      
      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP_ADDRESS }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          password: ${{ secrets.LIGHTSAIL_USER_PASSWORD }}
          port: 22
          script: |
            sudo apt-get install -y zip unzip
            unzip -q -o /home/${{ secrets.LIGHTSAIL_USERNAME }}/deployment.zip -d /home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ secrets.LIGHTSAIL_ROOT_DIR }}
            rm /home/${{ secrets.LIGHTSAIL_USERNAME }}/deployment.zip
            sudo systemctl restart nginx

